services:
  server:
    environment:
      - NODE_ENV=production
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:3000"
    volumes:
      - type: bind
        source: ./database.db
        target: /app/database.db
  # nginx:
  #   image: nginx:1.26.0-alpine
  #   restart: always
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf